// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDom = require("react-dom");
var Pervasives = require("rescript/lib/js/pervasives.js");
var User$MaarekjReasonFormGen = require("./User.bs.js");

function Example_Index$App(Props) {
  return React.createElement(User$MaarekjReasonFormGen.Form.make, {});
}

var App = {
  make: Example_Index$App
};

var app = document.querySelector("#app");

if (app == null) {
  Pervasives.failwith("#app not found");
} else {
  ReactDom.render(React.createElement(Example_Index$App, {}), app);
}

exports.App = App;
/* app Not a pure module */
